### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by pablomayobre** [kevin-d-omara/Pong#12]
Put your release files (`.zip` and `.love` files for distripution, maybe an `.app` MacOS X file for #7) in the [Releases](https://github.com/kevin-d-omara/Pong/releases) section that GitHub provides.

With this you could delete the pointless [Download](https://github.com/kevin-d-omara/Pong/tree/master/Downloads) folder which is really heavy and not nice when you want to fork or clone the repo

**Comment by kevin-d-omara** [comment]
Thank you Pablo!  I didn't realize GitHub had a Releases section.  I've made an .app for OSX that needs testing.  I'm going to test it tomorrow and then move the Download folder to the Releases.

**Comment by pablomayobre** [comment]
Glad it helped! good luck on this

**Comment by kevin-d-omara** [comment]
Thanks again for you help!  I've successfully tested the MacOS X app and it all checks out.  [Version 1.0.0 has been released!](https://github.com/kevin-d-omara/Pong/releases/tag/v1.0.0)
